# Site Settings
title: Yanqing Wang | Homepage
url: 'http://webjeda.com'
baseurl: ''
#baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Yanqing Wang
tagline: Undergraduate Student<br>at BUPT
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am now an undergraduate student in <a href="http://www.bupt.edu.cn" color="#545E6C">Beijing University of Posts and Telecommunications (BUPT)</a>, and have been a visiting researcher since Nov. 2016 in <a href="http://www.cslt.org/EN/">Center for Speech and Language Technologies (CSLT)</a>, Research Institute of Information Technology in Tsinghua University. My interest lays not only in signal processing and telecommunication theory, which are two main fields of my major, but also in deep learning and its application in speech recognition as well as activity recognition, in which I am doing some research work.'

#sidebar links
email: wangyanqingchn[at]163.com
#phone: 012 345 6789
#website: blog.webjeda.com #do not add http://
linkedin: yanqing-wang-36a591102
linkedin_name: Yanqing Wang
github: wyq730
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
